name: Build Docker Image

on:
  push:
    branches:
      - main
      - next
    # paths:
    #   - semantic/**/*

  pull_request:
    branches:
      - main
      - next
    types: [synchronize, closed, opened]
    # paths:
    #   - semantic/**/*

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup a builder for Docker build action.
      #
      # See: https://github.com/docker/setup-buildx-action
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Get Tags for Image
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ github.event.repository.name }}
      # Build the docker image.
      # TODO: Push the image to ECR or Docker Hub and enable dynamic tags.
      #
      # See: https://github.com/docker/build-push-action
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./semantic
          file: ./semantic/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          load: false
          tags: generators/test
          labels: ${{steps.metadata.outputs.labels}}

      - name: Lookup Images
        run: |
          echo ${{steps.metadata.outputs.tags}}
          echo ${{steps.metadata.outputs.labels}}
          docker images

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1

      # - name: Login to ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      # - name: Push image to ECR
      #   env:
      #     ECR_REGISTRY: ${{steps.login_ecr.outputs.registry}}
      #     ECR_REPOSITORY: ${{secrets.ECR_REPOSITORY}}
      #     IMAGE_TAG: ${{github.sha}}
      #   run: |
      #     docker push {ECR_REGISTRY}/{ECR_REPOSITORY}


