name: Release
on:
  push:
    branches:
      - main
      - next
    # paths:
    #   - semantic/**/*

  pull_request:
    branches:
      - main
      - next
    types: [synchronize, closed, opened]
    # paths:
    #   - semantic/**/*

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Gets semantic release info
      id: semantic_release_info
      uses: jossef/action-semantic-release-info@v1

    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
        cache-dependency-path: ./semantic/yarn.lock

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5.4

    - name: Get latest commit message
      run: |
          echo '::set-output name=title::${{ github.event.head_commit.message }}'
          echo '::set-output name=sha::${{ github.sha }}'
          echo '::set-output name=action::${{ github.ref }}'
      id: get_message

    # - name: Generate build number
    #   uses: einaregilsson/build-number@v3
    #   with:
    #     token: ${{secrets.github_token}}
    #   id: buildnumber

    - name: Setup
      working-directory: ./semantic
      run: |
          echo ${{steps.get_message.outputs.sha}}
          echo ${{steps.get_message.outputs.action}}
          yarn install --frozen-lockfile
          yarn build

    - name: Commit files
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "docs(): bumping release ${{ steps.semantic_release_info.outputs.git_tag }}"
          git tag ${{ steps.semantic_release_info.outputs.git_tag }}

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ github.token }}
        tags: true

    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.semantic_release_info.outputs.git_tag }}
        release_name: ${{ steps.semantic_release_info.outputs.git_tag }}
        body: ${{ steps.semantic_release_info.outputs.notes }}
        draft: false
        prerelease: false

    - name: Dry Run
      if: steps.branch-name.outputs.is_default == 'false'
      working-directory: ./semantic
      run: |
          yarn semantic-release --dry-run --no-ci

    - name: Gets semantic release info
      id: semantic_release_info
      uses: jossef/action-semantic-release-info@v1
      run: |
          echo ""

    # - name: Build Artifact
    #   if: contains(steps.get_message.outputs.title,'Merge pull request') && !contains(steps.get_message.outputs.title,'release')
    #   working-directory: ./semantic
    #   run:


    - name: Release
      if: contains(steps.get_message.outputs.title,'Merge pull request') && contains(steps.get_message.outputs.title,'release')
      working-directory: ./semantic
      run: yarn semantic-release
