name: Release
on:
  push:
    branches:
      - main
      - next
    # paths:
    #   - semantic/**/*

  pull_request:
    branches:
      - main
      - next
    types: [synchronize, closed, opened]
    # paths:
    #   - semantic/**/*

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout
      uses: actions/checkout@v3    
      
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
        cache-dependency-path: ./semantic/yarn.lock

    - name: Setup
      working-directory: ./semantic
      run: |          
          yarn install --frozen-lockfile
          yarn build

    - name: Release      
      if: "contains(github.base_ref, 'main') && contains(github.head_ref, 'release/')"
      working-directory: ./semantic
      run: yarn semantic-release
