name: Release
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check PR from release branch
      shell: bash
      run: echo "github.head_ref"
      id: get_branch
      
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
        cache-dependency-path: ./semantic/yarn.lock
    - name: Setup and release
      working-directory: ./semantic
      run: | 
          yarn install --frozen-lockfile
          yarn run build      
          yarn semantic-release            
