name: Release
on:
  push:
    branches:
      - main
    # paths:
    #   - semantic/**/*

  pull_request:
    branches:
      - main
    # paths:
    #   - semantic/**/*
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5.4
        
    - name: Running on the default branch.
      if: steps.branch-name.outputs.is_default == 'true'
      run: echo '::set-output name=PR::${{ steps.branch-name.outputs.current_branch }}'      
      id: default_branch
    
    - name: Running on a pull request branch.
      if: steps.branch-name.outputs.is_default == 'false'        
      run: |
          echo '::set-output name=PR::${{ steps.branch-name.outputs.current_branch }}'      
          echo '::set-output name=HEAD::${{ github.head_ref }}'
          echo '::set-output name=BASE::${{ github.base_ref }}'
      id: pull_request_branch

    # - name: Check if it is from release branch      
    #   if: steps.pull_request.outputs.PR != 'release/**/*'
    #   run: |
    #     echo '::set-output name=check_PR::release'
    #   id: check_PR
      
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
        cache-dependency-path: ./semantic/yarn.lock
    - name: Setup
      working-directory: ./semantic
      run: | 
          echo ${{steps.pull_request_branch.outputs.PR}}
          echo ${{steps.pull_request_branch.outputs.BASE}}
          yarn install --frozen-lockfile
          yarn run build      
    - name: Dry Run
      if: contains(github.head_ref, 'release/') && !github.event.pull_request.merged
      working-directory: ./semantic      
      run: yarn semantic-release --dry-run
    - name: Release
      if: "github.event.pull_request.merged"
      working-directory: ./semantic
      run: yarn semantic-release
