name: Upload DAGs

on:
  workflow_dispatch:
    inputs:
      upload:
        description: 'Upload DAGs'
        required: false

jobs:
  upload-dag:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'semantic'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check branch name
        run: |
          echo ${GITHUB_REF##*/}
          echo "acc/dec/${{inputs.upload}}/hhhh"

      - name: Check
        if: (${{inputs.upload}} == " ")
        run: echo "hello"
        

      # - name: Configure AWS Credentials
      #   if: contains(steps.get_message.outputs.title, 'Merge pull request') && contains(steps.get_message.outputs.title, 'release/')
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_CODEDEPLOY_ACCESS_KEY }}
      #     aws-secret-access-key: ${{ secrets.AWS_CODEDEPLOY_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1

      # - name: Upload dags to s3
      #   if: contains(steps.get_message.outputs.title, 'Merge pull request') && contains(steps.get_message.outputs.title, 'release/')
      #   run: |
      #     aws s3 cp ${{github.workspace}}/airflow-local-runner/dags s3://com.laudio.artifact./dags --exclude "*" --include "**.py" 